SERVER_IP: "10.170.10.33"
SERVER_PORT: 8000
COBOTTA_IP: "10.170.10.35"
COBOTTA_CLIENT_LOGGER_NAME: "Cobotta1_Client"
COBOTTA_SERVER_LOGGER_NAME: "Cobotta1_Server"
TIMEOUT: 5
LOGGER_LEVEL: "debug"
COBOTTA_CAMERA_IP: None
