SERVER_IP: "10.170.10.33"
SERVER_PORT: 8002
COBOTTA_IP: "10.170.10.36"
CLIENT_LOGGER_NAME: "Cobotta2_Client"
SERVER_LOGGER_NAME: "Cobotta2_Server"
TIMEOUT: 5
LOGGER_LEVEL: "debug"
COBOTTA_CAMERA_IP: "10.170.10.37"
