SERVER_IP: "10.170.10.33"
SERVER_PORT: 8003
COBOTTA_IP: "10.170.10.36"
CLIENT_LOGGER_NAME: "Cobotta2_State_Client"
SERVER_LOGGER_NAME: "Cobotta2_State_Server"
TIMEOUT: 5
LOGGER_LEVEL: "debug"
COBOTTA_CAMERA_IP: "10.170.10.37"
