SERVER_IP: "10.170.10.33"
SERVER_PORT: 8001
COBOTTA_IP: "10.170.10.35"
CLIENT_LOGGER_NAME: "Cobotta1_State_Client"
SERVER_LOGGER_NAME: "Cobotta1_State_Server"
TIMEOUT: 5
LOGGER_LEVEL: "debug"
COBOTTA_CAMERA_IP: None
